Improved parameters information for customizations

diff --git a/openshift-install-wrapper b/openshift-install-wrapper
--- a/openshift-install-wrapper
+++ b/openshift-install-wrapper
@@ -324,9 +324,10 @@ customize_cluster() {
   local clusterdir=${__clustersdir}/${INSTALLOPTS[name]}.${INSTALLOPTS[domain]}
   local client=${__bindir}/oc-${INSTALLOPTS[version]}
 
-  for script in $( echo ${SCRIPTS} | tr -s "," " " ); do
-    type ${script} &>/dev/null && out "→ Running $script..." || die "${script} not found."
-    ${script} ${script} ${clusterdir} ${client} ${VERBOSE} ${QUIET} ${INSTALLOPTS[*]}
+  for script in $( echo ${SCRIPTS} | tr -s ";" " " ); do
+    cmd=${script%%:*}
+    type ${cmd} &>/dev/null && out "→ Running ${cmd} customization..." || die "${cmd} not found."
+    ${cmd} ${script##*:} ${clusterdir} ${client} ${VERBOSE} ${QUIET} ${INSTALLOPTS[*]}
   done
 }
 
diff --git a/scripts/add-htpasswd-idp b/scripts/add-htpasswd-idp
--- a/scripts/add-htpasswd-idp
+++ b/scripts/add-htpasswd-idp
@@ -7,9 +7,36 @@
 # Mandatory function
 # start main - do not remove this line and do not change the function name
 main() {
-  # Users: admin, user, guest
-  # Passwords are generated based on the username
-  # Tip: function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
+  # read params from command line
+  IFS=',' read -r -a params <<< "${1}"
+
+  # check if there are custom users or use the default ones
+  if [ -z ${params[1]} ]; then
+    # Users: admin, user, guest
+    # Passwords are generated based on the username
+    # Tip: function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
+    HTPASSWD=YWRtaW46JGFwcjEkR2pDNi9TZHMkcTBWTElmaU5paE8vRXpNdmxNM2w3MAp1c2VyOiRhcHIxJDlQcGM4NnNvJE5NMEJCNFNzamNNbXgxTDlEU2FPMi8KZ3Vlc3Q6JGFwcjEkeWc1L1puTVkkZS5uSkROV0dNODlLQUVQVjVjSWY3MQo=
+    success "Adding default users: admin, user and guest."
+
+  else
+    success "Using custom users."
+    for index in "${!params[@]}"; do
+      # use -bc only for the first user
+      [ ${index} -eq 0 ] && htpasswdargs="-bc" || htpasswdargs="-b"
+
+      # add each user in the file
+      # NOTE: I tried to use bash substring extraction but failed when merging the script
+      user=$( echo ${params[index]} | cut -d = -f 1 )
+      password=$( echo ${params[index]} | cut -d = -f 2 )
+      htpasswd $htpasswdargs /tmp/htpasswd.tmp.$$ ${user} ${password} &>/dev/null \
+        && success "Adding user ${user} with password ${password}." \
+        || err "Error adding user ${password}. Skipping."
+    done
+
+    # get the base64 content and delete it
+    HTPASSWD=$( cat /tmp/htpasswd.tmp.$$ | base64 -w 0 )
+    rm -fr /tmp/htpasswd.tmp.$$
+  fi
 
   # Create htpassw-secret
   cat <<EOF | _oc apply -f - \
@@ -22,7 +49,7 @@ metadata:
   namespace: openshift-config
 type: Opaque
 data:
-  htpasswd: YWRtaW46JGFwcjEkR2pDNi9TZHMkcTBWTElmaU5paE8vRXpNdmxNM2w3MAp1c2VyOiRhcHIxJDlQcGM4NnNvJE5NMEJCNFNzamNNbXgxTDlEU2FPMi8KZ3Vlc3Q6JGFwcjEkeWc1L1puTVkkZS5uSkROV0dNODlLQUVQVjVjSWY3MQo=
+  htpasswd: ${HTPASSWD}
 EOF
 
   # Configure the OAuth/cluster
@@ -45,11 +72,6 @@ spec:
       fileData:
         name: htpasswd-secret
 EOF
-
-  # Add cluster-admin to "admin" user
-  _oc adm policy add-cluster-role-to-user cluster-admin admin \
-      && success "Role cluster-admin successfully added to \"admin\" user." \
-      || die "Error adding cluster-admin role to \"admin\" user."
 }
 # end main - do not remove this line
 
