Added cluster-admins group to add-htpasswd-idp customization

diff --git a/src/scripts/add-htpasswd-idp b/src/scripts/add-htpasswd-idp
--- a/src/scripts/add-htpasswd-idp
+++ b/src/scripts/add-htpasswd-idp
@@ -14,6 +14,14 @@ main() {
     exit
   fi
 
+  # create cluster-admins group and bind it to cluster-admin role
+  oc adm groups new cluster-admins \
+     && verbose "Group \"cluster-admins\" has been created." \
+     || err "Error creating \"cluster-admins\" group. Skipping."
+  oc adm policy add-cluster-role-to-group cluster-admin cluster-admins \
+     && verbose "Group \"cluster-admins\" has been granted cluster-admin permissions." \
+     || err "Error binding \"cluster-admins\" to cluster-admin cluster role. Skipping."
+
   # parse parameters from ${1}, if any
   if [[ ${1} == *"="* ]]; then
     success "Using custom users from command line parameters."
@@ -33,11 +41,11 @@ main() {
         && verbose "Adding user ${user} with password ${password}." \
         || err "Error adding user ${password}. Skipping."
 
-      # if the user is named "admin" add it as a cluster-admin
+      # if the user is named "admin" add it to cluster-admins group
       if [ "${user}" == "admin" ]; then
-        oc adm policy add-cluster-role-to-user cluster-admin admin \
-           && verbose "User \"admin\" has been configured as a cluster-admin." \
-           || err "Error adding \"admin\" as a cluster-admin. Skipping."
+        oc adm groups add-users cluster-admins admin \
+           && verbose "User \"admin\" has been added to cluster-admins group." \
+           || err "Error adding \"admin\" as a cluster-admins member. Skipping."
       fi
     done
 
@@ -51,9 +59,9 @@ main() {
     # Tip: function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
     HTPASSWD=YWRtaW46JGFwcjEkR2pDNi9TZHMkcTBWTElmaU5paE8vRXpNdmxNM2w3MAp1c2VyOiRhcHIxJDlQcGM4NnNvJE5NMEJCNFNzamNNbXgxTDlEU2FPMi8KZ3Vlc3Q6JGFwcjEkeWc1L1puTVkkZS5uSkROV0dNODlLQUVQVjVjSWY3MQo=
 
-    oc adm policy add-cluster-role-to-user cluster-admin admin \
-       && verbose "User \"admin\" has been configured as a cluster-admin." \
-       || err "Error adding \"admin\" as a cluster-admin. Skipping."
+    oc adm groups add-users cluster-admins admin \
+       && verbose "User \"admin\" has been added to cluster-admins group." \
+       || err "Error adding \"admin\" as a cluster-admins member. Skipping."
   fi
 
   # Create htpassw-secret
@@ -92,6 +100,8 @@ spec:
 EOF
 }
 # end main - do not remove this line
+
+  # Create a cluster-admins group
 
 # Optionally, keep this if you want to run your script manually or for testing.
 main $@
