Added "admin" users as cluster-admin by default

diff --git a/scripts/add-htpasswd-idp b/scripts/add-htpasswd-idp
--- a/scripts/add-htpasswd-idp
+++ b/scripts/add-htpasswd-idp
@@ -23,8 +23,15 @@ main() {
       user=$( echo ${params[index]} | cut -d = -f 1 )
       password=$( echo ${params[index]} | cut -d = -f 2 )
       htpasswd $htpasswdargs /tmp/htpasswd.tmp.$$ ${user} ${password} &>/dev/null \
-        && success "Adding user ${user} with password ${password}." \
+        && verbose "Adding user ${user} with password ${password}." \
         || err "Error adding user ${password}. Skipping."
+
+      # if the user is named "admin" add it as a cluster-admin
+      if [ "${user}" == "admin" ]; then
+        oc adm policy add-cluster-role-to-user cluster-admin admin \
+           && verbose "User \"admin\" has been configured as a cluster-admin." \
+           || err "Error adding \"admin\" as a cluster-admin. Skipping."
+      fi
     done
 
     # get the base64 content and delete it
@@ -36,6 +43,10 @@ main() {
     # Passwords are generated based on the username
     # Tip: function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
     HTPASSWD=YWRtaW46JGFwcjEkR2pDNi9TZHMkcTBWTElmaU5paE8vRXpNdmxNM2w3MAp1c2VyOiRhcHIxJDlQcGM4NnNvJE5NMEJCNFNzamNNbXgxTDlEU2FPMi8KZ3Vlc3Q6JGFwcjEkeWc1L1puTVkkZS5uSkROV0dNODlLQUVQVjVjSWY3MQo=
+
+    oc adm policy add-cluster-role-to-user cluster-admin admin \
+       && verbose "User \"admin\" has been configured as a cluster-admin." \
+       || err "Error adding \"admin\" as a cluster-admin. Skipping."
   fi
 
   # Create htpassw-secret
