Added _oc function to simplify the interaction with the cluster from the customizations Added install-rhsso-742 post-install customization

diff --git a/scripts/add-htpasswd-idp b/scripts/add-htpasswd-idp
--- a/scripts/add-htpasswd-idp
+++ b/scripts/add-htpasswd-idp
@@ -1,25 +1,35 @@
 #!/bin/bash
 
 # Optional fields
-# script name: add-htpasswd-identity-provider
+# script name: add-htpasswd-idp
 # script description: Install a sample htpasswd file with admin, user and guest users
 
 # Mandatory function
 # start main - do not remove this line and do not change the function name
 main() {
-  _oc="${3} --kubeconfig=${2}/auth/kubeconfig"
+  # Users: admin, user, guest
+  # Passwords are generated based on the username
+  # Tip: function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
 
-  # passwords are generated based on the username
-  # function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
-  htpasswd -bc htpasswd admin YWRtaW5h
-  htpasswd -b htpasswd user dXNlcnVz
-  htpasswd -b htpasswd guest Z3Vlc3Rn
+  # Create htpassw-secret
+  cat <<EOF | _oc apply -f - \
+                  && success "Secret htpasswd-secret created/configured successfully." \
+                  || die "Error creating htpasswd-secret."
+apiVersion: v1
+kind: Secret
+metadata:
+  name: htpasswd-secret
+  namespace: openshift-config
+type: Opaque
+data:
+  htpasswd: YWRtaW46JGFwcjEkR2pDNi9TZHMkcTBWTElmaU5paE8vRXpNdmxNM2w3MAp1c2VyOiRhcHIxJDlQcGM4NnNvJE5NMEJCNFNzamNNbXgxTDlEU2FPMi8KZ3Vlc3Q6JGFwcjEkeWc1L1puTVkkZS5uSkROV0dNODlLQUVQVjVjSWY3MQo=
+EOF
 
-  ${_oc} delete secret htpasswd-secret -n openshift-config || true
-  ${_oc} create secret generic htpasswd-secret --from-file htpasswd -n openshift-config
-  rm -fr htpasswd
-
-  echo "
+  # Configure the OAuth/cluster
+  # TODO: convert this in a patch command so it doesn't deletes other configured IDP
+  cat <<EOF | _oc apply -f - \
+                  && success "OAuth/cluster successfully configured." \
+                  || die "Error applying configuration to OAuth/cluster."
 apiVersion: config.openshift.io/v1
 kind: OAuth
 metadata:
@@ -34,8 +44,12 @@ spec:
     htpasswd:
       fileData:
         name: htpasswd-secret
-" | ${_oc} apply -f -
-  ${_oc} adm policy add-cluster-role-to-user cluster-admin admin
+EOF
+
+  # Add cluster-admin to "admin" user
+  _oc adm policy add-cluster-role-to-user cluster-admin admin \
+      && success "Role cluster-admin successfully added to \"admin\" user." \
+      || die "Error adding cluster-admin role to \"admin\" user."
 }
 # end main - do not remove this line
 
